apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators-application
  namespace: openshift-gitops
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/ocp-gitops/ocp-cluster.git'
    path: openshift-operators/overlays/default
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true